// <auto-generated />
namespace CarRent.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixuserrolesrelationonclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixuserrolesrelationonclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201706042027030_fix user-roles relation on class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
