// <auto-generated />
namespace CarRent.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Userclassaddedroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Userclassaddedroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201706020948403_User class added roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
